from pathlib import Path

STORAGE_BASE_DATA = "data"
SEARCHES_FOLDER = "searches"

BASE_DATA_PATH = Path(STORAGE_BASE_DATA)
SEARCHES_PATH = BASE_DATA_PATH / SEARCHES_FOLDER

JSON_INDENT = 2
FILE_ENCODIND = "utf-8"
